# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'OriginalApp' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for OriginalApp

  target 'OriginalAppTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'OriginalAppUITests' do
    # Pods for testing
  end
 pod 'NCMB', :git => 'https://github.com/NIFTYCloud-mbaas/ncmb_ios.git', :branch => 'develop'
 pod 'NYXImagesKit'
 pod 'UITextView+Placeholder'
 pod 'KRProgressHUD'
 pod 'PKHUD'
 pod 'SwiftData'
 pod 'RAMAnimatedTabBarController'
 pod 'IQKeyboardManagerSwift', '6.3.0'
 pod 'SkyFloatingLabelTextField', '~> 3.0'

end
